# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vneirinc <vneirinc@students.s19.be>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/30 22:38:58 by vneirinc          #+#    #+#              #
#    Updated: 2021/12/25 12:38:59 by vneirinc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    init: true
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    networks:
      - my_net
    #volumes:
    #  - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: always

networks:
  my_net:
