# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vneirinc <vneirinc@students.s19.be>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/30 22:38:58 by vneirinc          #+#    #+#              #
#    Updated: 2022/02/09 09:10:05 by vneirinc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Node anchor def: http://yaml.org/spec/1.2-old/spec.html#id2785586
networks:
  my_net:
    name: "my_net"

volumes:
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${VOL_DIR}/wordpress
  db:
    name: "db"
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: ${VOL_DIR}/db

services:
  nginx:
    init: true
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - &ver version=${ALPINE_VER}
        - &domain domain_name=${DOMAIN_NAME}
    environment:
      - WP_DIR=${WP_DIR}
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - my_net
    volumes:
      - &wp_vol wordpress:${WP_DIR}
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    init: true
    container_name: wordpress
    image: wordpress 
    build:
      context: ./requirements/wordpress
      args:
        - *ver
        - WP_DL=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PWD}
    networks:
      - my_net
    volumes:
      - *wp_vol
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    init: true
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - *ver
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PWD}
      - MYSQL_ROOT_PWD=${MYSQL_ROOT_PWD}
    networks:
      - my_net
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

  vsftpd:
    init: true
    container_name: vsftpd
    image: vsftpd
    build:
      context: ./bonus/vsftpd
      args:
        - *ver
    environment:
      - FTP_DIR=/var/www/
      - FTP_USER=ftp_wp
      - FTP_PWD=ftp_wp
    volumes:
      - *wp_vol
    ports:
      - "20:20"
      - "21:21"
      - "990:990"
      - "40000-40100:40000-40100"
    depends_on:
      - wordpress
    restart: unless-stopped

  redis:
    init: true
    container_name: redis
    image: redis
    build:
      context: ./bonus/redis
      args:
        - *ver
    networks:
      - my_net
    expose:
      - "6379"
    depends_on:
      - wordpress
    restart: unless-stopped

  adminer:
    init: true
    container_name: adminer
    image: adminer
    build:
      context: ./bonus/adminer
      args:
        - *ver
        - ADMINER_DL=https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-mysql.php
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PWD}
    networks:
      - my_net
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: unless-stopped
