# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vneirinc <vneirinc@students.s19.be>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/30 22:38:58 by vneirinc          #+#    #+#              #
#    Updated: 2021/12/28 11:01:55 by vneirinc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Node anchor def: http://yaml.org/spec/1.2-old/spec.html#id2785586
networks:
  my_net:
    name: "my_net"

volumes:
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: local
      o: bind
      device: /Users/victorneirinckx/Desktop/19/Inception/wordpress
  db:
    name: "db"
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /Users/victorneirinckx/Desktop/19/Inception/db

services:
  nginx:
    init: true
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - &version version=3.14.3
    env_file:
      - .env
    networks:
      - my_net
    volumes:
      - &wp_vol wordpress:/var/www/wp_dir
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    init: true
    container_name: wordpress
    image: wordpress 
    build:
      context: ./requirements/wordpress
      args:
        - *version
    env_file:
      - .env
    networks:
      - my_net
    volumes:
      - *wp_vol
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    init: true
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - *version
    env_file:
      - .env
    networks:
      - my_net
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

