# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vneirinc <vneirinc@students.s19.be>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/30 22:38:58 by vneirinc          #+#    #+#              #
#    Updated: 2022/01/02 12:16:12 by vneirinc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Node anchor def: http://yaml.org/spec/1.2-old/spec.html#id2785586
networks:
  my_net:
    name: "my_net"

volumes:
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: local
      o: bind
      device: /Users/victorneirinckx/Desktop/19/Inception/wop
  db:
    name: "db"
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /Users/victorneirinckx/Desktop/19/Inception/dabb

services:
  nginx:
    init: true
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - &ver version=${ALPINE_VER}
        - &domain domain_name=${DOMAIN_NAME}
    env_file:
      - .env
    networks:
      - my_net
    volumes:
      - &wp_vol wordpress:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    init: true
    container_name: wordpress
    image: wordpress 
    build:
      context: ./requirements/wordpress
      args:
        - *ver
    env_file:
      - .env
    networks:
      - my_net
    volumes:
      - *wp_vol
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    init: true
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - *ver
    env_file:
      - .env
    networks:
      - my_net
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

  vsftpd:
    init: true
    container_name: vsftpd
    image: vsftpd
    build:
      context: ./bonus/vsftpd
      args:
        - *ver
    env_file:
      - .env
    environment:
      - FTP_DIR=/var/www/
      - FTP_USER=ftp_wp
      - FTP_PWD=ftp_wp
    volumes:
      - *wp_vol
    ports:
      - "20:20"
      - "21:21"
      - "990:990"
      - "40000-40100:40000-40100"
    depends_on:
      - wordpress
    restart: unless-stopped

  redis:
    init: true
    container_name: redis
    image: redis
    build:
      context: ./bonus/redis
      args:
        - *ver
    env_file:
      - .env
    networks:
      - my_net
    expose:
      - "6379"
    depends_on:
      - wordpress
    restart: unless-stopped

  adminer:
    init: true
    container_name: adminer
    image: adminer
    build:
      context: ./bonus/adminer
      args:
        - *ver
    env_file:
      - .env
    networks:
      - my_net
    expose:
      - "9001"
    depends_on:
      - mariadb
    restart: unless-stopped

