# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vneirinc <vneirinc@student.s19.be>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/30 22:38:58 by vneirinc          #+#    #+#              #
#    Updated: 2022/02/10 15:00:12 by vneirinc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

networks:
  my_net:
    name: "my_net"

volumes:
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${VOL_DIR}/wordpress
  db:
    name: "db"
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: ${VOL_DIR}/db

services:
  nginx:
    init: true
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - &ver version=${ALPINE_VER}
    environment:
      - WP_DIR=${WP_DIR}
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - my_net
    volumes:
      - &wp_vol wordpress:${WP_DIR}
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    init: true
    container_name: wordpress
    image: wordpress 
    build:
      context: ./requirements/wordpress
      args:
        - *ver
        - WP_DL=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    environment:
      - URL=${URL}
      - TITLE=${TITLE}
      - WP_DIR=${WP_DIR}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_MAIL=${WP_USER_MAIL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PWD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - my_net
    volumes:
      - *wp_vol
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    init: true
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - *ver
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PWD}
      - MYSQL_ROOT_PWD=${MYSQL_ROOT_PWD}
    networks:
      - my_net
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

  redis:
    init: true
    container_name: redis
    image: redis
    build:
      context: ./bonus/redis
      args:
        - *ver
    networks:
      - my_net
    expose:
      - "6379"
    depends_on:
      - wordpress
    restart: unless-stopped

